/**
 * ESP32 secrets file
 * 
 * Contains information required to connect to WiFi and in-turn, AWS IoT
 * 
 * Authors: Vipul Deshpande, Jaime Burbano
 */


/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include <pgmspace.h>

#define SECRET
#define THINGNAME "SubscriberG03"

const char WIFI_SSID[] = "UPC2687429";
const char WIFI_PASSWORD[] = "TAdvrnjad5u5";
const char AWS_IOT_ENDPOINT[] = "a3vjjrz30hahlq-ats.iot.us-east-2.amazonaws.com";

/* Amazon Root CA 1 */
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

/* Device Certificate */
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIVAPvUDMcc2yFY4CdTh6qwRWMeeWMMMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMDExMjAxODMy
MzNaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6w0q2EgF5zbpUSX5V
pmcX7PX53/I4sBQVC+0WoQnNo+jXBVEAki5riMAUJBEBLEbIltvTTpb+Wskk5D4z
uN/T6r0nnisisppj9ogGtmX2/nsDOF0ZjtYb08vmXjrbAsNdEHXIHlKJMaPtpo68
LPkp4PmlxZPyHE7+vY54/wpI/5XVeAu/XmwCqxDk+7fPbmlPw0C2iI3MQySKdcAl
+XOBC+UaRzlVAaJyRyRkK0KFo8RN+r7mPow8nxK8cLmzL4tKB5NTlPqUgS5ETkRi
s3ArLsfeGar+JFEGVelkxah0O8A8+3qVKThWmuoWVEu/9CYYVS3sK078m8dmAZav
a2WNAgMBAAGjYDBeMB8GA1UdIwQYMBaAFJOr5/8YIYaIeuvKG6YRGWCmjnnwMB0G
A1UdDgQWBBT5+JfqPuVlQMEDtXvV5nTbNdkoIDAMBgNVHRMBAf8EAjAAMA4GA1Ud
DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAa505X7VaHc1Cod6VA/348mzO
JeeUWLuai/xuYUSudvpi8d8sNTZ9Z0vfmqdaRhcEGQwSh2kApDOrn8J/v7y6KNf2
dxadyEOQhNCWdtnbbiB/ZGq/Hyb4xi8aotL4XEBsImApYsre6cp6NQZQolOijg4j
tc/a6dfM7dq+1/UZ98awgWmGF9Qk1djlgWa5ypafGajpdts9FdUDCNJmQTjdUZd7
qYYzBpurRuT0Cq+b/72dXoQQSebsfKE/+7X3d/gUZvWadXK8SeI7s37Owmo6PLO2
0vC6CxAezGMG4B8qtfOOhP3XtUXMOa/X/flO3PhqO987oSFTWoSjkbDflzADyA==
-----END CERTIFICATE-----
)KEY";

/* Device Private Key */
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAusNKthIBec26VEl+VaZnF+z1+d/yOLAUFQvtFqEJzaPo1wVR
AJIua4jAFCQRASxGyJbb006W/lrJJOQ+M7jf0+q9J54rIrKaY/aIBrZl9v57Azhd
GY7WG9PL5l462wLDXRB1yB5SiTGj7aaOvCz5KeD5pcWT8hxO/r2OeP8KSP+V1XgL
v15sAqsQ5Pu3z25pT8NAtoiNzEMkinXAJflzgQvlGkc5VQGickckZCtChaPETfq+
5j6MPJ8SvHC5sy+LSgeTU5T6lIEuRE5EYrNwKy7H3hmq/iRRBlXpZMWodDvAPPt6
lSk4VprqFlRLv/QmGFUt7CtO/JvHZgGWr2tljQIDAQABAoIBACMaXcqG69wW/PSm
s6Yplqr6kOkcXIynG78w9KkSL6OFMVho2WbAExWHKIMgnEmaJtvA7yRyWxMHwVK7
y60xDHDqaA8wPW9SHo63Ya3RTqzz++8JAwawwDGOx35PK8TKaint1BV/DYhX2jXq
3l0kHtjuPj4YOsyA4aAjxMmdNjOt9CqKRjYjIMeGZhHNqLu3CW1w366lkDeP0NWf
3NvpKDn25CxCS3UAXCBHT4M7jok7052idGo7rGwzBOvRIz0QNb5GVuRL+KfphqpN
Dq0E8hcNVLFi6C4jzX+A4sXdO3700uLPdaDyXO5n7NcGHNiL15cD2P20Fj3UAYBb
T5OECAECgYEA3Gx2a3D6BQ6MHaWmKWc+RYSZpTFRwPLTrXXTrPMiPByoPknmVBxA
DorKdqNCIhzIIHah8qgOSIuHc0Bhv/6FsmrkF4dljB3nO4JrebjEREaFoKQZoawn
Hy4QHOPIHwihFisRbFpqV/gGXPkgX6L/JX+eCdUwKh46Nvsd92K45QECgYEA2OgF
OgwcBKNrGyVR7c/l4XIVAmd4FMZ7IwF/piLhGyVlD93rRZWd2Y3iWf0Ig1whqOG8
mEWrHhPyJkNcw3V+72PQHwLItEDv2fz0r5pwNVQb64Yn6Avecalrs1diLe5x2cC6
8/5PXA0thtwM5TMY1CVCTRUWlAQItjFYlo3BRI0CgYApTG0XjlBZ2DLqbxnl0gE5
1zFOYSI3K4f7jQL++YLljlz7Zq8v/ScHUnvCpK4EZC4e3vtS0qfycaoMLvjhlxeH
qT1ZJzYgfY3QeYwXf0XOoQPyaCyhPPcLgX7lWswo/F3qIGGgUoRwPPk8PDUTlh+F
8BY1M2tVyNoRaRVhP27zAQKBgGpAJadMnUDsaB/xBRQQHdR0lLQLyTesDk+UgVn5
hflNNRczpvb8FkmmhfV8zHnEXLykb0TMA8mFDb4Oi1c3rAlKBH3cWEJr+NH4ZkfK
yCJnZBHYMp4pijp1Okush2xmfCClly7EKU23KtD/49U2VXg+FB88MEYrP7U3sOR2
5fBVAoGBAMLkg8z6tZmO7sFeoAEYOuFxvp8NS3+O2gnyY7Vh/4zLfF1ci1SpkDn1
PR7bNzEa+bpIW0CP09GPtr/vM9zywdyE8jpoUmbHNp/l6WoI+fX6UjCW5649LW1R
uycAwMQKNAJfPnZKQlVzk7IoNyQxr+6Uz1bw9+nGnut+xURY8VbL
-----END RSA PRIVATE KEY-----
)KEY";